"""add unique constraint to paquete nombre

Revision ID: 34725b57b658
Revises: 42297467f5e2
Create Date: 2026-08-25 02:17:00.847251

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = '34725b57b658'
down_revision = '42297467f5e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paquete', schema=None) as batch_op:
        batch_op.create_unique_constraint(
            'uq_paquete_nombre',
            ['nombre']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paquete', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uq_paquete_nombre',
            type_='unique'
        )

    # ### end Alembic commands ###
