"""add paquete and paquete servicio models

Revision ID: 42297467f5e2
Revises: 04e66a2dc56f
Create Date: 2026-08-22 02:51:44.122923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42297467f5e2'
down_revision = '04e66a2dc56f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paquete',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('precio_total', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paquete_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paquete_id', sa.Integer(), nullable=False),
    sa.Column('servicio_id', sa.Integer(), nullable=False),
    sa.Column('num_sesiones', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paquete_id'], ['paquete.id'], ),
    sa.ForeignKeyConstraint(['servicio_id'], ['servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paquete_paciente', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_paquete_paciente_paquete_id_paquete', 'paquete', ['paquete_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paquete_paciente', schema=None) as batch_op:
        batch_op.drop_constraint('fk_paquete_paciente_paquete_id_paquete', type_='foreignkey')

    op.drop_table('paquete_servicio')
    op.drop_table('paquete')
    # ### end Alembic commands ###
