"""sistema de invites y auth de paciente

Revision ID: a9319846ad7c
Revises: 31ba0cc519d1
Create Date: 2026-09-02 19:26:07.610769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9319846ad7c'
down_revision = '31ba0cc519d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinica_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CLIENTE', 'ASISTENTE', 'ESPECIALISTA', name='tipoinvite'), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=False),
    sa.Column('expira', sa.DateTime(), nullable=False),
    sa.Column('creado_por_usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['clinica_id'], ['clinica.id'], ),
    sa.ForeignKeyConstraint(['creado_por_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), server_default='1', nullable=False))
        batch_op.create_unique_constraint('uq_paciente_clinica_email', ['clinica_id', 'email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint('uq_paciente_clinica_email', type_='unique')
        batch_op.drop_column('activo')
        batch_op.drop_column('google_id')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('email')

    op.drop_table('invite')
    # ### end Alembic commands ###
