"""add google_id and email

Revision ID: f7417f1596a8
Revises: a9319846ad7c
Create Date: 2026-09-04 03:36:33.620404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7417f1596a8'
down_revision = 'a9319846ad7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('paciente_cedula_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('paciente_telefono_key'), type_='unique')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_id')

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('paciente_telefono_key'), ['telefono'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('paciente_cedula_key'), ['cedula'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
